### ISSUE TITLE
Collect manifests

### ISSUE THREAD

**Issue by AminMasoudi** [cpu-simulation/DevOps#2]
# Collect Manifests Files to DevOps Repo

### TODO
- [ ] collect evaluation team manifests
- [ ] collect simulation-01  files
- [ ] write some manifests for others
  - [ ] use Helm chart
