### ISSUE TITLE
Nexus registry

### ISSUE THREAD

**Issue by AminMasoudi** [cpu-simulation/DevOps#3]
# Create and config a docker registry with Nexus

### TODO

- [ ] store all docker files on that
  - [ ] all simulation images
  - [ ] evaluation
    - [ ] evaluation-rest
    - [ ] evaluation-tester
    - [ ] evaluation-frontend
    - [ ] mysql
    - [ ] influxdb
    - [ ] pometheus
    - [ ] grafana
    - [ ] rabbit-mq
  - [ ] git sync
- [ ] build and push to this repo
  - [ ] simulations
  - [ ] evaluation
